[package]
name = "geo-collate"
version = "0.1.0"
authors = ["Joe Sadusk <joe@sadusk.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo-types = "0.6"

[dev-dependencies]
geo = "0.14"
